dojot/backstage

- src/graphql/schema/utils/MapPermissions.json
Just Add endpoint Firmware Image 
This PR is connected to dojot/dojot#833.
> Add endpoint Firmware Image

- src/graphql/schema/utils/MapPermissions.json
This PR is connected to dojot/dojot#833.
> Add more endpoints

- src/graphql/schema/Schema.js
- src/graphql/schema/helpers/PermissionsHelper.js
Bug fix
Add catch to avoid some problemas
> Fix: Add catch

- src/graphql/schema/Schema.js
- src/graphql/schema/utils/AxiosUtils.js
Bug fix
Instead of use  the internal route, it was use the external. 
use  the internal route
This PR is connected to dojot/dojot#833.
> Fix route to internal request

- .travis.yml
- package-lock.json
- package.json
- src/docs/GenerateFileSchema.js
- src/graphql/Schema.js
- src/graphql/template/Resolvers.js
- src/travis/deploy-gh-pages.sh
feature
Now, It will Auto generate the Documentation.
This PR is connected to [dojot/dojot#871](https://github.com/dojot/dojot/issues/871).
> Documentation

- src/graphql/template/Resolvers.js
- src/tests/apiMock/template.js
- src/tests/graphql/resolvers/Template.test.js
- src/tests/graphql/test-cases/template/GetTemplate.js
Bug
Fix reserved Label
* This PR is connected to [dojot/dojot#951](https://github.com/dojot/dojot/issues/951).
>  Fix reserved Label for FW

- src/graphql/auth/helpers/MapPermissions.json
This PR is connected to dojot/dojot#1081;
This PR is connected to dojot/dojot#1082;
This PR is connected to dojot/dojot#1083;
>  fix: All history,Endpoints groups and permissions and Remove endpoint /metric

- src/graphql/auth/helpers/MapPermissions.json
Change the  Viewer -> Modifier
This PR is connected to dojot/dojot#1085
> fix: Change the location of the checkbox for the Certificate Sign permission

- src/graphql/auth/helpers/MapPermissions.json
Remove the ro_import permission
Remove the all_export permission
This is connected to dojot/dojot#1086
This is connected to dojot/dojot#1087
> fix: Remove the all_export and ro_import permission

- src/graphql/auth/helpers/MapPermissions.json
> iotagent-mqtt - Add service metrics mqqt

- src/graphql/auth/helpers/MapPermissions.json
permission for import was total
permission for import should be just POST
This is connected to dojot/dojot#1087
> fix: permission for import should be just POST

- src/graphql/auth/helpers/MapPermissions.json
The certificate retrieval mechanism has been changed to support the new x509 identity component.
Certificate retrieval used an old EJBCA route.
The new behavior is to generate the certificate using the EJBCA of the new x509 identity component.
This change has an impact on the …
> Support for the new x509-identity-mgmt component

- src/graphql/Schema.js
- src/graphql/device/Resolvers.js
> feature - Add sortBy on device query

- src/graphql/device/Resolvers.js
- src/tests/graphql/resolvers/Device.test.js
Bug Fix
Results are not sent in guaranteed order
Sorting is done on the results to be returned
No
dojot/dojot#1672
> Ordering values for the dashboard

- src/graphql/device/Resolvers.js
- src/tests/graphql/resolvers/Device.test.js
Co-authored-by: Luis Felipe Furlan Cruz <lfcruz@cpqd.com.br>
> Ordering values for the dashboard (#53)

- src/graphql/device/Resolvers.js
- src/tests/graphql/resolvers/Device.test.js
Data is returned from oldest to newest
Data returns from newest to oldest
No
dojot/dojot#1675
> Changed sorting to ascending

- LICENSE
- license-exceptions.json
- package-lock.json
- package.json
> [dev] Changed license to Apache 2.0 

- LICENSE
- license-exceptions.json
- package-lock.json
- package.json
> [v0.5.2] Cherry-picking licenses from development 

- LICENSE
- license-exceptions.json
- package-lock.json
- package.json
Be careful, see if it is necessary to update the branch! **Most likely it is not to update.**
> Merge version v0.5.2 from branch release/v0.5.2 to branch master

- src/graphql/device/Resolvers.js
Bug Fix
The variable is not initialized, allowing its value to be empty
The variable is now initialized to a default value, preventing the value from being empty
No
dojot/dojot#2046
> fix: Set default value for the lastN parameter

- src/graphql/device/Helpers.js
> Adding an additional type of spelling for boolean

- src/graphql/device/Helpers.js
Bug Fix
Boolean value is not being handled correctly
Added check to correctly handle Boolean values
No
dojot/dojot#2096
> fix: Correct handling for truly Boolean values

- .gitignore
- api/v1.yml
- app/express/routes/v1/Auth.js
- app/keycloak/Utils.js
- app/keycloak/index.js
- example/docker-compose.yml
- example/keycloak/admin_realm.json
- example/kong/kong.config.sh
- tests/integration/express/RoutesV1.test.js
> chore: add complete auth configs in example and url config acc in user-info

- app/Utils.js
- app/express/interceptors/Proxy.js
- app/graphql/utils/AxiosUtils.js
- app/keycloak/index.js
- app/redis/RedisManagement.js
- config/default.conf
- config/development.conf
- example/docker-compose.yml
- package-lock.json
- package.json
- readme.md
- tests/integration/Keycloak.test.js
- tests/integration/Redis.test.js
- tests/integration/Utils.test.js
- tests/integration/express/RoutesV1.test.js
- tests/integration/graphql/GraphQL.test.js
- tests/integration/graphql/resolvers/DeviceResolver.test.js
- tests/integration/graphql/resolvers/TemplateResolver.test.js
- tests/integration/graphql/resolvers/UserResolver.test.js
- tests/unit/App.test.js
> fixings in tls/ssl to using https in proxy, graphql e keycloak 

- .gitignore
- app/graphql/device/Helpers.js
- app/graphql/device/Resolvers.js
- app/graphql/device/TypeDefs.js
- tests/integration/graphql/resolvers/DeviceResolver.test.js
feature
The code is not up to date with the development branch
The code has been updated with development changes
dojot/dojot#2110
> Sync with development branch

- .gitignore
- schema.graphql
- src/operations/device/TypeDefs.js
- src/operations/device/helpers.js
- src/operations/device/query.getDeviceById.js
- src/services/service.device.js
- src/services/service.template.js
- src/tests/graphql/resolvers/Device.test.js
improvement
getDeviceById returns few fields
added more fields to the device
No
dojot/dojot#2358
> Improved getDeviceById query

- schema.graphql
- src/Schema.js
- src/operations/security/Resolvers.js
- src/operations/security/TypeDefs.js
- src/operations/security/query.getCertificateList.js
- src/services/service.security.js
- src/tests/graphql/resolvers/Security.test.js
feat
query for listing certificates
No
dojot/dojot#2303
> feat: Added certificate listing

- src/Schema.js
- src/operations/device/Resolvers.js
- src/operations/device/mutation.editDevice.js
- src/services/service.device.js
- src/tests/graphql/resolvers/Device.test.js
- src/utils/Object.js
Feature
No mutation to edit device
The mentioned mutation was created
dojot/dojot#2332
> Feature - Edit Device Mutation

- .gitignore
- schema.graphql
- src/operations/device/TypeDefs.js
- src/operations/device/query.getDeviceById.js
- src/operations/device/query.getDevices.js
- src/operations/template/query.getTemplates.js
- src/tests/graphql/resolvers/Device.test.js
Fix
getTemplates query returned fields are not correct
They are correct now
> Fix getTemplates Query Returned Fields

- src/operations/device/TypeDefs.js
- src/operations/device/mutation.createDevice.js
> Fix - Create Device Mutation

- src/Schema.js
- src/operations/security/Resolvers.js
- src/operations/security/TypeDefs.js
- src/operations/security/mutation.createCertificationAuthority.js
- src/operations/security/mutation.deleteCertificationAuthorities.js
- src/operations/security/query.getCertificationAuthorities.js
- src/services/service.security.js
Feature
Missing queries and mutations for certification authorities
Queries and mutations were created
No
dojot/dojot#2373
> Feature - CA Queries Mutations

- src/Schema.js
- src/operations/device/TypeDefs.js
- src/operations/device/mutation.createDevice.js
- src/operations/device/query.getDevices.js
- src/operations/security/Resolvers.js
- src/operations/security/helpers.js
- src/operations/security/mutation.associateDevice.js
- src/operations/security/mutation.disassociateDevice.js
- src/operations/security/query.getCertificateByFingerprint.js
- src/operations/security/query.getCertificateById.js
- src/services/service.security.js
- src/tests/graphql/resolvers/Device.test.js
> security flow in device creation

- src/Schema.js
- src/operations/security/Resolvers.js
- src/operations/security/TypeDefs.js
- src/operations/security/mutation.createCertificateCSR.js
- src/operations/security/mutation.createCertificateOneClick.js
- src/operations/security/mutation.registerExternalCertificate.js
- src/services/service.security.js
> Feature: Mutations for create certificate with CSR and register external certificate

- src/operations/device/query.getDeviceById.js
- src/tests/graphql/resolvers/Device.test.js
Feature
The certificate fingerprint is not returned by the getDeviceById query
It is returned now
No
dojot/dojot#2433
> Nx Feature - 2433 - Show Associated Certificate

- .eslintignore
- .eslintrc
- .eslintrc.js
- src/operations/security/TypeDefs.js
- src/operations/security/helpers.js
- src/operations/security/mutation.createCertificateCSR.js
- src/operations/security/mutation.createCertificateOneClick.js
- src/services/service.security.js
Added CA certificate on return
Bug fix
> Fix private key header

- src/operations/device/mutation.deleteDevices.js
feature
dojot/dojot#2494
On delete a device, the device is disassociated of the certificate.
> Issue#2494: disassociate device on delete

- .eslintrc
- src/operations/device/mutation.deleteDevices.js
Fix
Failed to run because the file extension was missing in an import
Now is working and I added a rule in the eslint config to prevent this type of error.
No
No
> Fix - Security Service Import

- src/databaseCheck.js
- src/operations/configuration/query.getConfig.js
> Fix: Issue 2588 - When accessing the Dashboard tosts are being displayed on the screen.

- src/operations/device/TypeDefs.js
- src/operations/template/TypeDefs.js
- src/operations/template/query.getTemplateById.js
- src/operations/template/query.getTemplates.js
https://dojot.atlassian.net/browse/DOJOT-77
Linked with: https://github.com/dojot/gui-v2/pull/199
> [DOJOT-77] Return Created Date

- src/operations/device/mutation.createDevice.js
- src/operations/template/TypeDefs.js
- src/routers/GraphQL.js
Feature
Axios error response data is not returned to front-end.
Now it is
No
https://dojot.atlassian.net/browse/DOJOT-75
https://dojot.atlassian.net/browse/DOJOT-76
> [DOJOT-75] [DOJOT-76] Feature - Unique Labels 

- src/operations/device/mutation.deleteDevices.js
- src/operations/device/query.getDeviceById.js
- src/operations/device/query.getDevices.js
- src/operations/security/TypeDefs.js
- src/operations/security/query.getCertificateById.js
- src/operations/security/query.getCertificateList.js
- src/operations/security/query.getCertificationAuthorities.js
- src/operations/template/TypeDefs.js
- src/operations/template/query.getTemplates.js
- src/services/service.device.js
- src/services/service.security.js
https://dojot.atlassian.net/browse/DOJOT-96
> [DOJOT-96] Feature - Sorting

- src/operations/device/Resolvers.js
- src/operations/device/TypeDefs.js
- src/operations/device/mutation.createMultipleDevices.js
- src/operations/template/Resolvers.js
- src/operations/template/TypeDefs.js
- src/operations/template/mutation.deleteMultipleTemplates.js
- src/services/service.template.js
> Feature - Actions in Batch

- src/tests/graphql/resolvers/User.test.js
- src/utils/SessionValidation.js
Fix
Tests broken
Fix tests
No
No
> Fix - Unit Tests

- src/operations/device/query.getDeviceById.js
- src/services/service.device.js
Bug fix
getting details fails if one of the calls fails.
if a history call fails, the response is built anyway
No
> Handling influx data recovery error in device details

- package-lock.json
- src/operations/device/TypeDefs.js
- src/operations/device/mutation.createDevice.js
- src/operations/device/mutation.editDevice.js
- src/operations/device/query.getDeviceById.js
- src/operations/device/query.getDevices.js
- src/tests/graphql/resolvers/Device.test.js
- yarn.lock
feature
can not disabled device
now device can be disabled
yes
https://dojot.atlassian.net/browse/DOJOT-141
https://dojot.atlassian.net/browse/DOJOT-143
> [DOJOT-141] [DOJOT-143] Create device with on or off state.

- src/operations/device/Resolvers.js
- src/operations/device/TypeDefs.js
- src/operations/device/mutation.actuate.js
- src/services/service.device.js
- src/tests/graphql/resolvers/Device.test.js
Feature
Cannot send values to device (actuation).
Now it is possible
No
https://dojot.atlassian.net/browse/DOJOT-194
> [DOJOT-194] Feature - Actuate

- DockerFile
> Update backstage Dockerfile to accept healthcheck

- src/services/service.device.js
No cenário de busca de atributos para a tela de detalhes do dispositivo:
Obtém dados a partir do endpoint 
`/tss/v1/devices/:device_id/data`
Ao inves de 
`/tss/v1/devices/:device_id/attrs/:attr/data`
O possível ponto de problema é quando o dispositivo com 4 atributos, por exemplo, envia uma mensagem contendo 2, seguido duma mensagem contendo os outros 2 atributos.
Com isso, não há como garantir que todos os ultimos valores sejam retornados, mas no cenário da bosch esse cenário não ocorre - e não acho que justifique esse tratamento a essa altura.
> [DOJOT-207] Utiliza query unificada para tela de detalhes

- src/operations/template/TypeDefs.js
- src/operations/template/mutation.deleteMultipleTemplates.js
- src/services/service.device.js
- src/services/service.template.js
https://dojot.atlassian.net/browse/DOJOT-52
> [DOJOT-52] - Feat: delete templates in batch integration

- src/operations/device/TypeDefs.js
Fix
Fail to delete devices.
Fixed
No
No
> Fix - Delete Devices Mutation

- src/Flow/locales.js
- src/Flow/nodes.js
- src/Schema.js
- src/index.js
- src/operations/device/TypeDefs.js
- src/operations/flow/Resolvers.js
- src/operations/flow/TypeDefs.js
- src/operations/flow/mutation.createFlow.js
- src/operations/flow/mutation.deleteFlow.js
- src/operations/flow/mutation.editFlow.js
- src/operations/flow/query.getFlowByID.js
- src/operations/flow/query.getFlows.js
- src/operations/flow/query.getNodes.js
- src/routers/Flow.js
- src/services/service.flows.js
feature
flow has no backstage route
flow routes were mapped from backstage
No
[DOJOT-190](https://dojot.atlassian.net/browse/DOJOT-190)
> Added flow APIs
